
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LolService", targetNamespace = "http://services/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LolService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "hitMe", targetNamespace = "http://services/", className = "client.HitMe")
    @ResponseWrapper(localName = "hitMeResponse", targetNamespace = "http://services/", className = "client.HitMeResponse")
    @Action(input = "http://services/LolService/hitMeRequest", output = "http://services/LolService/hitMeResponse")
    public void hitMe(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doMe", targetNamespace = "http://services/", className = "client.DoMe")
    @ResponseWrapper(localName = "doMeResponse", targetNamespace = "http://services/", className = "client.DoMeResponse")
    @Action(input = "http://services/LolService/doMeRequest", output = "http://services/LolService/doMeResponse")
    public String doMe();

}
