
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LolServiceService", targetNamespace = "http://services/", wsdlLocation = "http://localhost:8080/lolservice?wsdl")
public class LolServiceService
    extends Service
{

    private final static URL LOLSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException LOLSERVICESERVICE_EXCEPTION;
    private final static QName LOLSERVICESERVICE_QNAME = new QName("http://services/", "LolServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/lolservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOLSERVICESERVICE_WSDL_LOCATION = url;
        LOLSERVICESERVICE_EXCEPTION = e;
    }

    public LolServiceService() {
        super(__getWsdlLocation(), LOLSERVICESERVICE_QNAME);
    }

    public LolServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOLSERVICESERVICE_QNAME, features);
    }

    public LolServiceService(URL wsdlLocation) {
        super(wsdlLocation, LOLSERVICESERVICE_QNAME);
    }

    public LolServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOLSERVICESERVICE_QNAME, features);
    }

    public LolServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LolServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LolService
     */
    @WebEndpoint(name = "LolServicePort")
    public LolService getLolServicePort() {
        return super.getPort(new QName("http://services/", "LolServicePort"), LolService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LolService
     */
    @WebEndpoint(name = "LolServicePort")
    public LolService getLolServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services/", "LolServicePort"), LolService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOLSERVICESERVICE_EXCEPTION!= null) {
            throw LOLSERVICESERVICE_EXCEPTION;
        }
        return LOLSERVICESERVICE_WSDL_LOCATION;
    }

}
